language: python
sudo: false
cache: pip
env:
  global:
    MOZ_HEADLESS=1
  matrix:
  - TOXENV=py27-dj18
  - TOXENV=py27-dj19
  - TOXENV=py27-dj110
  - TOXENV=py27-dj111
  - TOXENV=py34-dj18
  - TOXENV=py34-dj19
  - TOXENV=py34-dj110
  - TOXENV=py34-dj111
  - TOXENV=py34-dj20
  # - TOXENV=py34-djdev
  # - TOXENV=py36-djdev
matrix:
  allow_failures:
    - env: TOXENV=py34-djdev
    - env: TOXENV=py36-djdev
install:
  - pip install tox codecov

script:
  - tox -v

after_success:
  #- coverage combine
  - codecov
